--- # indicate yml file
- name: Install and start Nginx
  hosts: all
  become: root # switch the user to root

  tasks:
   - name: Install Nginx
     apt: 
       name: nginx
       state: present
   - name: Start Nginx
     service:
       name: nginx
       state: started
